### PR TITLE
Restricts spel-release so it will only install on matching EL version

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Comment by lorengordon** [comment]
Broke open the [repos stored as build artifacts](https://github.com/plus3it/spel-repo-builder/actions/runs/6332397565?pr=178), to confirm the expected Requires statements:

```
Requires:       redhat-release >=  8, redhat-release < 9

Requires:       redhat-release >=  7, redhat-release < 8
```

**Review by ferricoxide — COMMENTED** [review]
Looks like this works on EL8 (at least Oracle 8):

~~~
$ rpm -qa \*release\*
redhat-release-8.8-0.8.el8.x86_64
epel-release-8-19.el8.noarch
redhat-release-eula-8.8-0.8.el8.x86_64
spel-release-8-3.noarch
~~~

But may not work on  EL9 (at least not CentOS _Stream_)

~~~bash
$ !rpm
rpm -qa \*-release
epel-next-release-9-7.el9.noarch
epel-release-9-7.el9.noarch
centos-stream-release-9.0-23.el9.noarch
~~~

**Comment by ferricoxide** [comment]
Ok, it's a _stream_ thing, not a CentOS thing:
~~~bash
$ rpm -qa \*release\*
epel-next-release-8-19.el8.noarch
epel-release-8-19.el8.noarch
spel-release-8-3.noarch
centos-stream-release-8.6-1.el8.noarch
~~~
Which is to say, it shouldn't install when generating CentOS Stream AMIs or already-running CentOS Stream EC2s (whether running version 8 or version 9)

**Comment by lorengordon** [comment]
We already install this on the steam Amis that we build, so, we already know it must be ok? In fact, the build itself installs the package successfully into a stream8 docker container. It definitely is working.

**Review by ferricoxide — APPROVED** [review]
N/m. CentOS Stream is setting `centos-stream-release` as a functional stand-in for `redhat-release`

~~~bash
$ rpm -q --whatprovides redhat-release
centos-stream-release-9.0-23.el9.noarch

$ rpm -q --whatprovides redhat-release --qf '%{version}\n'
9.0
~~~

**Pull request merged**
